name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  DEFMT_LOG: "off"
  RUSTUP_TOOLCHAIN: stable

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf
          components: rust-src

      - name: Install espflash binary
        run: |
          gh release download -R esp-rs/espflash -p "espflash-x86_64-unknown-linux-gnu.zip"
          unzip espflash-x86_64-unknown-linux-gnu.zip
          chmod +x espflash
          sudo mv espflash /usr/local/bin/
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Release Binary
        run: cargo build --release --target riscv32imac-unknown-none-elf -Z build-std=core,alloc
        env:
          RUSTC_BOOTSTRAP: 1

      - name: Create Binaries
        run: |
          # 1. Die kleine Datei (nur App-Image, ca. 73KB - 150KB)
          espflash save-image --chip esp32c6 target/riscv32imac-unknown-none-elf/release/komsi2tacho komsi2tacho_app_only.bin
          
          # 2. Die gro√üe Datei (Full-Flash-Image mit Bootloader, 4MB)
          espflash save-image --chip esp32c6 --merge target/riscv32imac-unknown-none-elf/release/komsi2tacho komsi2tacho_full_4mb.bin

      - name: Zip Artifact
        run: |
          zip komsi2tacho_${{ github.ref_name }}.zip komsi2tacho_app_only.bin komsi2tacho_full_4mb.bin

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: komsi2tacho_${{ github.ref_name }}.zip

