name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  DEFMT_LOG: "off"
  RUSTUP_TOOLCHAIN: stable

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf
          components: rust-src

      - name: Install espflash binary
        run: |
          gh release download -R esp-rs/espflash -p "espflash-x86_64-unknown-linux-gnu.zip"
          unzip espflash-x86_64-unknown-linux-gnu.zip
          chmod +x espflash
          sudo mv espflash /usr/local/bin/
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Extract Version
        id: get_version
        run: |
          # Extrahiert die Version aus der Cargo.toml
          VERSION=$(grep '^version =' Cargo.toml | cut -d '"' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Release Binary
        run: cargo build --release --target riscv32imac-unknown-none-elf -Z build-std=core,alloc
        env:
          RUSTC_BOOTSTRAP: 1

      - name: Convert ELF to Flashable Binary
        run: |
          espflash save-image --chip esp32c6 target/riscv32imac-unknown-none-elf/release/komsi2tacho komsi2tacho_esp32c6.bin

      - name: Zip Artifact
        run: |
          # Erstellt das Zip mit der Versionsnummer im Namen
          zip komsi2tacho_v${{ env.VERSION }}.zip komsi2tacho_esp32c6.bin

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # Findet automatisch die Datei mit der Versionsnummer
          files: komsi2tacho_v${{ env.VERSION }}.zip
