name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  DEFMT_LOG: "off"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf
          components: rust-src

      - name: Install espflash via binstall
        run: |
          # Installiert binstall, falls nicht vorhanden, und dann espflash als Binary
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com | sh
          cargo binstall espflash --confirm

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Release Binary
        run: cargo build --release

      - name: Convert ELF to Flashable Binary
        run: |
          # Wir nutzen hier den Pfad aus deiner Cargo.toml name = "komsi2tacho"
          cargo espflash save-image --chip esp32c6 target/riscv32imac-unknown-none-elf/release/komsi2tacho komsi2tacho_esp32c6.bin

      - name: Zip Artifact
        run: zip komsi2tacho.zip komsi2tacho_esp32c6.bin

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: komsi2tacho.zip
