name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  DEFMT_LOG: "off"
  RUSTUP_TOOLCHAIN: stable

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf
          components: rust-src

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Release Binary
        run: cargo build --release --target riscv32imac-unknown-none-elf -Z build-std=core,alloc
        env:
          RUSTC_BOOTSTRAP: 1

      - name: Prepare Artifacts
        run: |
          cp target/riscv32imac-unknown-none-elf/release/komsi2tacho komsi2tacho_esp32c6.elf
          
          # Erstelle das ZIP mit der ELF-Datei
          zip komsi2tacho_${{ github.ref_name }}.zip komsi2tacho_esp32c6.elf

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: komsi2tacho_${{ github.ref_name }}.zip


